HOST_UBOOT_TOOLS_CONF_ENV = CFLAGS="$(HOST_CFLAGS) -std=gnu99"
UBOOT_TOOLS_CONF_ENV = CFLAGS="$(TARGET_CFLAGS) -std=gnu99"

UBOOT_TOOLS_MAKE_OPTS += CFLAGS="$(TARGET_CFLAGS) -std=gnu99" HOSTCFLAGS="$(HOST_CFLAGS) -std=gnu99"
